/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HighsInfo extends HighsInfoStruct {
  private transient long swigCPtr;

  protected HighsInfo(long cPtr, boolean cMemoryOwn) {
    super(highsJNI.HighsInfo_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighsInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HighsInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HighsInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HighsInfo() {
    this(highsJNI.new_HighsInfo__SWIG_0(), true);
  }

  public HighsInfo(HighsInfo info) {
    this(highsJNI.new_HighsInfo__SWIG_1(HighsInfo.getCPtr(info), info), true);
  }

  public void invalidate() {
    highsJNI.HighsInfo_invalidate(swigCPtr, this);
  }

  public void invalidateKkt() {
    highsJNI.HighsInfo_invalidateKkt(swigCPtr, this);
  }

  public void invalidatePrimalKkt() {
    highsJNI.HighsInfo_invalidatePrimalKkt(swigCPtr, this);
  }

  public void invalidateDualKkt() {
    highsJNI.HighsInfo_invalidateDualKkt(swigCPtr, this);
  }

  public boolean equal(HighsInfo info_) {
    return highsJNI.HighsInfo_equal(swigCPtr, this, HighsInfo.getCPtr(info_), info_);
  }

  public void setRecords(SWIGTYPE_p_std__vectorT_InfoRecord_p_t value) {
    highsJNI.HighsInfo_records_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_InfoRecord_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_InfoRecord_p_t getRecords() {
    long cPtr = highsJNI.HighsInfo_records_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_InfoRecord_p_t(cPtr, false);
  }

}
