/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HighsProfiling {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HighsProfiling(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighsProfiling obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HighsProfiling obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HighsProfiling(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTimer(SWIGTYPE_p_HighsTimer value) {
    highsJNI.HighsProfiling_timer_set(swigCPtr, this, SWIGTYPE_p_HighsTimer.getCPtr(value));
  }

  public SWIGTYPE_p_HighsTimer getTimer() {
    long cPtr = highsJNI.HighsProfiling_timer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_HighsTimer(cPtr, false);
  }

  public void setMulti_threaded(boolean value) {
    highsJNI.HighsProfiling_multi_threaded_set(swigCPtr, this, value);
  }

  public boolean getMulti_threaded() {
    return highsJNI.HighsProfiling_multi_threaded_get(swigCPtr, this);
  }

  public void setModel_name_(String value) {
    highsJNI.HighsProfiling_model_name__set(swigCPtr, this, value);
  }

  public String getModel_name_() {
    return highsJNI.HighsProfiling_model_name__get(swigCPtr, this);
  }

  public void setSub_solver_(boolean value) {
    highsJNI.HighsProfiling_sub_solver__set(swigCPtr, this, value);
  }

  public boolean getSub_solver_() {
    return highsJNI.HighsProfiling_sub_solver__get(swigCPtr, this);
  }

  public void setMip_(boolean value) {
    highsJNI.HighsProfiling_mip__set(swigCPtr, this, value);
  }

  public boolean getMip_() {
    return highsJNI.HighsProfiling_mip__get(swigCPtr, this);
  }

  public void setNum_profiling_clock_(long value) {
    highsJNI.HighsProfiling_num_profiling_clock__set(swigCPtr, this, value);
  }

  public long getNum_profiling_clock_() {
    return highsJNI.HighsProfiling_num_profiling_clock__get(swigCPtr, this);
  }

  public void setName(SWIGTYPE_p_std__vectorT_std__string_t value) {
    highsJNI.HighsProfiling_name_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getName() {
    long cPtr = highsJNI.HighsProfiling_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public void setSubmip(SWIGTYPE_p_std__vectorT_unsigned_char_t value) {
    highsJNI.HighsProfiling_submip_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t getSubmip() {
    long cPtr = highsJNI.HighsProfiling_submip_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_unsigned_char_t(cPtr, false);
  }

  public void setRecord(SWIGTYPE_p_std__vectorT_HighsProfilingRecord_t value) {
    highsJNI.HighsProfiling_record_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_HighsProfilingRecord_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_HighsProfilingRecord_t getRecord() {
    long cPtr = highsJNI.HighsProfiling_record_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_HighsProfilingRecord_t(cPtr, false);
  }

  public void setSubmip_record(SWIGTYPE_p_std__vectorT_HighsProfilingRecord_t value) {
    highsJNI.HighsProfiling_submip_record_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_HighsProfilingRecord_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_HighsProfilingRecord_t getSubmip_record() {
    long cPtr = highsJNI.HighsProfiling_submip_record_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_HighsProfilingRecord_t(cPtr, false);
  }

  public void setInitialized(boolean value) {
    highsJNI.HighsProfiling_initialized_set(swigCPtr, this, value);
  }

  public boolean getInitialized() {
    return highsJNI.HighsProfiling_initialized_get(swigCPtr, this);
  }

  public void initialize(SWIGTYPE_p_HighsTimer timer_, boolean subsolver_profiling, boolean mip_profiling) {
    highsJNI.HighsProfiling_initialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_HighsTimer.getCPtr(timer_), subsolver_profiling, mip_profiling);
  }

  public void initialize(SWIGTYPE_p_HighsTimer timer_, boolean subsolver_profiling) {
    highsJNI.HighsProfiling_initialize__SWIG_1(swigCPtr, this, SWIGTYPE_p_HighsTimer.getCPtr(timer_), subsolver_profiling);
  }

  public void clear() {
    highsJNI.HighsProfiling_clear(swigCPtr, this);
  }

  public long numThread() {
    return highsJNI.HighsProfiling_numThread(swigCPtr, this);
  }

  public long myThread() {
    return highsJNI.HighsProfiling_myThread(swigCPtr, this);
  }

  public void setSubMip(boolean submip) {
    highsJNI.HighsProfiling_setSubMip(swigCPtr, this, submip);
  }

  public boolean isSubMip() {
    return highsJNI.HighsProfiling_isSubMip(swigCPtr, this);
  }

  public HighsProfilingRecord getHighsProfilingRecord(long record_type) {
    long cPtr = highsJNI.HighsProfiling_getHighsProfilingRecord__SWIG_0(swigCPtr, this, record_type);
    return (cPtr == 0) ? null : new HighsProfilingRecord(cPtr, false);
  }

  public HighsProfilingRecord getHighsProfilingRecord() {
    long cPtr = highsJNI.HighsProfiling_getHighsProfilingRecord__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new HighsProfilingRecord(cPtr, false);
  }

  public void start(long profiling_clock, boolean restart) {
    highsJNI.HighsProfiling_start__SWIG_0(swigCPtr, this, profiling_clock, restart);
  }

  public void start(long profiling_clock) {
    highsJNI.HighsProfiling_start__SWIG_1(swigCPtr, this, profiling_clock);
  }

  public void stop(long profiling_clock) {
    highsJNI.HighsProfiling_stop(swigCPtr, this, profiling_clock);
  }

  public double read(long profiling_clock, long record_type) {
    return highsJNI.HighsProfiling_read__SWIG_0(swigCPtr, this, profiling_clock, record_type);
  }

  public double read(long profiling_clock) {
    return highsJNI.HighsProfiling_read__SWIG_1(swigCPtr, this, profiling_clock);
  }

  public boolean running(long profiling_clock, long record_type) {
    return highsJNI.HighsProfiling_running__SWIG_0(swigCPtr, this, profiling_clock, record_type);
  }

  public boolean running(long profiling_clock) {
    return highsJNI.HighsProfiling_running__SWIG_1(swigCPtr, this, profiling_clock);
  }

  public long numCall(long profiling_clock, long record_type) {
    return highsJNI.HighsProfiling_numCall__SWIG_0(swigCPtr, this, profiling_clock, record_type);
  }

  public long numCall(long profiling_clock) {
    return highsJNI.HighsProfiling_numCall__SWIG_1(swigCPtr, this, profiling_clock);
  }

  public void solveCall(String model, boolean submip) {
    highsJNI.HighsProfiling_solveCall(swigCPtr, this, model, submip);
  }

  public HighsProfiling() {
    this(highsJNI.new_HighsProfiling(), true);
  }

}
