/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public interface highsConstants {
  public final static String CMAKE_BUILD_TYPE = highsJNI.CMAKE_BUILD_TYPE_get();
  public final static String HIGHS_GITHASH = highsJNI.HIGHS_GITHASH_get();
  public final static int HIGHS_VERSION_MAJOR = highsJNI.HIGHS_VERSION_MAJOR_get();
  public final static int HIGHS_VERSION_MINOR = highsJNI.HIGHS_VERSION_MINOR_get();
  public final static int HIGHS_VERSION_PATCH = highsJNI.HIGHS_VERSION_PATCH_get();
}
