/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsRunDataType {
  public final static HighsRunDataType kInt64 = new HighsRunDataType("kInt64", highsJNI.HighsRunDataType_kInt64_get());
  public final static HighsRunDataType kInt = new HighsRunDataType("kInt", highsJNI.HighsRunDataType_kInt_get());
  public final static HighsRunDataType kDouble = new HighsRunDataType("kDouble");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsRunDataType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsRunDataType.class + " with value " + swigValue);
  }

  private HighsRunDataType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsRunDataType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsRunDataType(String swigName, HighsRunDataType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsRunDataType[] swigValues = { kInt64, kInt, kDouble };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

