/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HighsInfoStruct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HighsInfoStruct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighsInfoStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HighsInfoStruct obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HighsInfoStruct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValid(boolean value) {
    highsJNI.HighsInfoStruct_valid_set(swigCPtr, this, value);
  }

  public boolean getValid() {
    return highsJNI.HighsInfoStruct_valid_get(swigCPtr, this);
  }

  public void setMip_node_count(long value) {
    highsJNI.HighsInfoStruct_mip_node_count_set(swigCPtr, this, value);
  }

  public long getMip_node_count() {
    return highsJNI.HighsInfoStruct_mip_node_count_get(swigCPtr, this);
  }

  public void setSimplex_iteration_count(long value) {
    highsJNI.HighsInfoStruct_simplex_iteration_count_set(swigCPtr, this, value);
  }

  public long getSimplex_iteration_count() {
    return highsJNI.HighsInfoStruct_simplex_iteration_count_get(swigCPtr, this);
  }

  public void setIpm_iteration_count(long value) {
    highsJNI.HighsInfoStruct_ipm_iteration_count_set(swigCPtr, this, value);
  }

  public long getIpm_iteration_count() {
    return highsJNI.HighsInfoStruct_ipm_iteration_count_get(swigCPtr, this);
  }

  public void setCrossover_iteration_count(long value) {
    highsJNI.HighsInfoStruct_crossover_iteration_count_set(swigCPtr, this, value);
  }

  public long getCrossover_iteration_count() {
    return highsJNI.HighsInfoStruct_crossover_iteration_count_get(swigCPtr, this);
  }

  public void setPdlp_iteration_count(long value) {
    highsJNI.HighsInfoStruct_pdlp_iteration_count_set(swigCPtr, this, value);
  }

  public long getPdlp_iteration_count() {
    return highsJNI.HighsInfoStruct_pdlp_iteration_count_get(swigCPtr, this);
  }

  public void setQp_iteration_count(long value) {
    highsJNI.HighsInfoStruct_qp_iteration_count_set(swigCPtr, this, value);
  }

  public long getQp_iteration_count() {
    return highsJNI.HighsInfoStruct_qp_iteration_count_get(swigCPtr, this);
  }

  public void setPrimal_solution_status(long value) {
    highsJNI.HighsInfoStruct_primal_solution_status_set(swigCPtr, this, value);
  }

  public long getPrimal_solution_status() {
    return highsJNI.HighsInfoStruct_primal_solution_status_get(swigCPtr, this);
  }

  public void setDual_solution_status(long value) {
    highsJNI.HighsInfoStruct_dual_solution_status_set(swigCPtr, this, value);
  }

  public long getDual_solution_status() {
    return highsJNI.HighsInfoStruct_dual_solution_status_get(swigCPtr, this);
  }

  public void setBasis_validity(long value) {
    highsJNI.HighsInfoStruct_basis_validity_set(swigCPtr, this, value);
  }

  public long getBasis_validity() {
    return highsJNI.HighsInfoStruct_basis_validity_get(swigCPtr, this);
  }

  public void setObjective_function_value(double value) {
    highsJNI.HighsInfoStruct_objective_function_value_set(swigCPtr, this, value);
  }

  public double getObjective_function_value() {
    return highsJNI.HighsInfoStruct_objective_function_value_get(swigCPtr, this);
  }

  public void setMip_dual_bound(double value) {
    highsJNI.HighsInfoStruct_mip_dual_bound_set(swigCPtr, this, value);
  }

  public double getMip_dual_bound() {
    return highsJNI.HighsInfoStruct_mip_dual_bound_get(swigCPtr, this);
  }

  public void setMip_gap(double value) {
    highsJNI.HighsInfoStruct_mip_gap_set(swigCPtr, this, value);
  }

  public double getMip_gap() {
    return highsJNI.HighsInfoStruct_mip_gap_get(swigCPtr, this);
  }

  public void setMax_integrality_violation(double value) {
    highsJNI.HighsInfoStruct_max_integrality_violation_set(swigCPtr, this, value);
  }

  public double getMax_integrality_violation() {
    return highsJNI.HighsInfoStruct_max_integrality_violation_get(swigCPtr, this);
  }

  public void setNum_primal_infeasibilities(long value) {
    highsJNI.HighsInfoStruct_num_primal_infeasibilities_set(swigCPtr, this, value);
  }

  public long getNum_primal_infeasibilities() {
    return highsJNI.HighsInfoStruct_num_primal_infeasibilities_get(swigCPtr, this);
  }

  public void setMax_primal_infeasibility(double value) {
    highsJNI.HighsInfoStruct_max_primal_infeasibility_set(swigCPtr, this, value);
  }

  public double getMax_primal_infeasibility() {
    return highsJNI.HighsInfoStruct_max_primal_infeasibility_get(swigCPtr, this);
  }

  public void setSum_primal_infeasibilities(double value) {
    highsJNI.HighsInfoStruct_sum_primal_infeasibilities_set(swigCPtr, this, value);
  }

  public double getSum_primal_infeasibilities() {
    return highsJNI.HighsInfoStruct_sum_primal_infeasibilities_get(swigCPtr, this);
  }

  public void setNum_dual_infeasibilities(long value) {
    highsJNI.HighsInfoStruct_num_dual_infeasibilities_set(swigCPtr, this, value);
  }

  public long getNum_dual_infeasibilities() {
    return highsJNI.HighsInfoStruct_num_dual_infeasibilities_get(swigCPtr, this);
  }

  public void setMax_dual_infeasibility(double value) {
    highsJNI.HighsInfoStruct_max_dual_infeasibility_set(swigCPtr, this, value);
  }

  public double getMax_dual_infeasibility() {
    return highsJNI.HighsInfoStruct_max_dual_infeasibility_get(swigCPtr, this);
  }

  public void setSum_dual_infeasibilities(double value) {
    highsJNI.HighsInfoStruct_sum_dual_infeasibilities_set(swigCPtr, this, value);
  }

  public double getSum_dual_infeasibilities() {
    return highsJNI.HighsInfoStruct_sum_dual_infeasibilities_get(swigCPtr, this);
  }

  public void setNum_semi_infeasibilities(long value) {
    highsJNI.HighsInfoStruct_num_semi_infeasibilities_set(swigCPtr, this, value);
  }

  public long getNum_semi_infeasibilities() {
    return highsJNI.HighsInfoStruct_num_semi_infeasibilities_get(swigCPtr, this);
  }

  public void setMax_semi_infeasibility(double value) {
    highsJNI.HighsInfoStruct_max_semi_infeasibility_set(swigCPtr, this, value);
  }

  public double getMax_semi_infeasibility() {
    return highsJNI.HighsInfoStruct_max_semi_infeasibility_get(swigCPtr, this);
  }

  public void setSum_semi_infeasibilities(double value) {
    highsJNI.HighsInfoStruct_sum_semi_infeasibilities_set(swigCPtr, this, value);
  }

  public double getSum_semi_infeasibilities() {
    return highsJNI.HighsInfoStruct_sum_semi_infeasibilities_get(swigCPtr, this);
  }

  public void setNum_relative_primal_infeasibilities(long value) {
    highsJNI.HighsInfoStruct_num_relative_primal_infeasibilities_set(swigCPtr, this, value);
  }

  public long getNum_relative_primal_infeasibilities() {
    return highsJNI.HighsInfoStruct_num_relative_primal_infeasibilities_get(swigCPtr, this);
  }

  public void setMax_relative_primal_infeasibility(double value) {
    highsJNI.HighsInfoStruct_max_relative_primal_infeasibility_set(swigCPtr, this, value);
  }

  public double getMax_relative_primal_infeasibility() {
    return highsJNI.HighsInfoStruct_max_relative_primal_infeasibility_get(swigCPtr, this);
  }

  public void setNum_relative_dual_infeasibilities(long value) {
    highsJNI.HighsInfoStruct_num_relative_dual_infeasibilities_set(swigCPtr, this, value);
  }

  public long getNum_relative_dual_infeasibilities() {
    return highsJNI.HighsInfoStruct_num_relative_dual_infeasibilities_get(swigCPtr, this);
  }

  public void setMax_relative_dual_infeasibility(double value) {
    highsJNI.HighsInfoStruct_max_relative_dual_infeasibility_set(swigCPtr, this, value);
  }

  public double getMax_relative_dual_infeasibility() {
    return highsJNI.HighsInfoStruct_max_relative_dual_infeasibility_get(swigCPtr, this);
  }

  public void setNum_primal_residual_errors(long value) {
    highsJNI.HighsInfoStruct_num_primal_residual_errors_set(swigCPtr, this, value);
  }

  public long getNum_primal_residual_errors() {
    return highsJNI.HighsInfoStruct_num_primal_residual_errors_get(swigCPtr, this);
  }

  public void setMax_primal_residual_error(double value) {
    highsJNI.HighsInfoStruct_max_primal_residual_error_set(swigCPtr, this, value);
  }

  public double getMax_primal_residual_error() {
    return highsJNI.HighsInfoStruct_max_primal_residual_error_get(swigCPtr, this);
  }

  public void setNum_dual_residual_errors(long value) {
    highsJNI.HighsInfoStruct_num_dual_residual_errors_set(swigCPtr, this, value);
  }

  public long getNum_dual_residual_errors() {
    return highsJNI.HighsInfoStruct_num_dual_residual_errors_get(swigCPtr, this);
  }

  public void setMax_dual_residual_error(double value) {
    highsJNI.HighsInfoStruct_max_dual_residual_error_set(swigCPtr, this, value);
  }

  public double getMax_dual_residual_error() {
    return highsJNI.HighsInfoStruct_max_dual_residual_error_get(swigCPtr, this);
  }

  public void setNum_relative_primal_residual_errors(long value) {
    highsJNI.HighsInfoStruct_num_relative_primal_residual_errors_set(swigCPtr, this, value);
  }

  public long getNum_relative_primal_residual_errors() {
    return highsJNI.HighsInfoStruct_num_relative_primal_residual_errors_get(swigCPtr, this);
  }

  public void setMax_relative_primal_residual_error(double value) {
    highsJNI.HighsInfoStruct_max_relative_primal_residual_error_set(swigCPtr, this, value);
  }

  public double getMax_relative_primal_residual_error() {
    return highsJNI.HighsInfoStruct_max_relative_primal_residual_error_get(swigCPtr, this);
  }

  public void setNum_relative_dual_residual_errors(long value) {
    highsJNI.HighsInfoStruct_num_relative_dual_residual_errors_set(swigCPtr, this, value);
  }

  public long getNum_relative_dual_residual_errors() {
    return highsJNI.HighsInfoStruct_num_relative_dual_residual_errors_get(swigCPtr, this);
  }

  public void setMax_relative_dual_residual_error(double value) {
    highsJNI.HighsInfoStruct_max_relative_dual_residual_error_set(swigCPtr, this, value);
  }

  public double getMax_relative_dual_residual_error() {
    return highsJNI.HighsInfoStruct_max_relative_dual_residual_error_get(swigCPtr, this);
  }

  public void setNum_complementarity_violations(long value) {
    highsJNI.HighsInfoStruct_num_complementarity_violations_set(swigCPtr, this, value);
  }

  public long getNum_complementarity_violations() {
    return highsJNI.HighsInfoStruct_num_complementarity_violations_get(swigCPtr, this);
  }

  public void setMax_complementarity_violation(double value) {
    highsJNI.HighsInfoStruct_max_complementarity_violation_set(swigCPtr, this, value);
  }

  public double getMax_complementarity_violation() {
    return highsJNI.HighsInfoStruct_max_complementarity_violation_get(swigCPtr, this);
  }

  public void setPrimal_dual_objective_error(double value) {
    highsJNI.HighsInfoStruct_primal_dual_objective_error_set(swigCPtr, this, value);
  }

  public double getPrimal_dual_objective_error() {
    return highsJNI.HighsInfoStruct_primal_dual_objective_error_get(swigCPtr, this);
  }

  public void setPrimal_dual_integral(double value) {
    highsJNI.HighsInfoStruct_primal_dual_integral_set(swigCPtr, this, value);
  }

  public double getPrimal_dual_integral() {
    return highsJNI.HighsInfoStruct_primal_dual_integral_get(swigCPtr, this);
  }

  public HighsInfoStruct() {
    this(highsJNI.new_HighsInfoStruct(), true);
  }

}
