/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class InfoRecord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InfoRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InfoRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(InfoRecord obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_InfoRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(HighsInfoType value) {
    highsJNI.InfoRecord_type_set(swigCPtr, this, value.swigValue());
  }

  public HighsInfoType getType() {
    return HighsInfoType.swigToEnum(highsJNI.InfoRecord_type_get(swigCPtr, this));
  }

  public void setName(String value) {
    highsJNI.InfoRecord_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return highsJNI.InfoRecord_name_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    highsJNI.InfoRecord_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return highsJNI.InfoRecord_description_get(swigCPtr, this);
  }

  public void setAdvanced(boolean value) {
    highsJNI.InfoRecord_advanced_set(swigCPtr, this, value);
  }

  public boolean getAdvanced() {
    return highsJNI.InfoRecord_advanced_get(swigCPtr, this);
  }

  public InfoRecord(HighsInfoType Xtype, String Xname, String Xdescription, boolean Xadvanced) {
    this(highsJNI.new_InfoRecord(Xtype.swigValue(), Xname, Xdescription, Xadvanced), true);
  }

}
