/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class InfoRecordDouble extends InfoRecord {
  private transient long swigCPtr;

  protected InfoRecordDouble(long cPtr, boolean cMemoryOwn) {
    super(highsJNI.InfoRecordDouble_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InfoRecordDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(InfoRecordDouble obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_InfoRecordDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setValue(SWIGTYPE_p_double value) {
    highsJNI.InfoRecordDouble_value_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getValue() {
    long cPtr = highsJNI.InfoRecordDouble_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setDefault_value(double value) {
    highsJNI.InfoRecordDouble_default_value_set(swigCPtr, this, value);
  }

  public double getDefault_value() {
    return highsJNI.InfoRecordDouble_default_value_get(swigCPtr, this);
  }

  public InfoRecordDouble(String Xname, String Xdescription, boolean Xadvanced, SWIGTYPE_p_double Xvalue_pointer, double Xdefault_value) {
    this(highsJNI.new_InfoRecordDouble(Xname, Xdescription, Xadvanced, SWIGTYPE_p_double.getCPtr(Xvalue_pointer), Xdefault_value), true);
  }

}
