/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class PdlpRestartStrategy {
  public final static PdlpRestartStrategy kPdlpRestartStrategyOff = new PdlpRestartStrategy("kPdlpRestartStrategyOff", highsJNI.kPdlpRestartStrategyOff_get());
  public final static PdlpRestartStrategy kPdlpRestartStrategyMin = new PdlpRestartStrategy("kPdlpRestartStrategyMin", highsJNI.kPdlpRestartStrategyMin_get());
  public final static PdlpRestartStrategy kPdlpRestartStrategyFixed = new PdlpRestartStrategy("kPdlpRestartStrategyFixed");
  public final static PdlpRestartStrategy kPdlpRestartStrategyAdaptive = new PdlpRestartStrategy("kPdlpRestartStrategyAdaptive");
  public final static PdlpRestartStrategy kPdlpRestartStrategyHalpern = new PdlpRestartStrategy("kPdlpRestartStrategyHalpern");
  public final static PdlpRestartStrategy kPdlpRestartStrategyMax = new PdlpRestartStrategy("kPdlpRestartStrategyMax", highsJNI.kPdlpRestartStrategyMax_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PdlpRestartStrategy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PdlpRestartStrategy.class + " with value " + swigValue);
  }

  private PdlpRestartStrategy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PdlpRestartStrategy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PdlpRestartStrategy(String swigName, PdlpRestartStrategy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PdlpRestartStrategy[] swigValues = { kPdlpRestartStrategyOff, kPdlpRestartStrategyMin, kPdlpRestartStrategyFixed, kPdlpRestartStrategyAdaptive, kPdlpRestartStrategyHalpern, kPdlpRestartStrategyMax };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

